const nodemailer = require('nodemailer');
const config = require('../config');

/**
 * Convert basic markdown to HTML for email rendering.
 */
function markdownToHtml(text) {
  let html = text;
  // Convert **bold** to <strong>
  html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
  // Convert *italic* to <em>
  html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');
  // Convert ### headers
  html = html.replace(/^### (.*?)$/gm, '<h3>$1</h3>');
  // Convert ## headers
  html = html.replace(/^## (.*?)$/gm, '<h2 style="color:#6C63FF;border-bottom:2px solid #6C63FF;padding-bottom:5px;">$1</h2>');
  // Convert # headers
  html = html.replace(/^# (.*?)$/gm, '<h1 style="color:#6C63FF;">$1</h1>');
  // Convert numbered lists
  html = html.replace(/^\d+\. (.*?)$/gm, '<li>$1</li>');
  // Convert bullet points
  html = html.replace(/^- (.*?)$/gm, '<li>$1</li>');
  // Convert double newlines to paragraphs
  html = html.replace(/\n\n/g, '</p><p>');
  // Convert single newlines to <br>
  html = html.replace(/\n/g, '<br>');
  return html;
}

/**
 * Build a professional HTML email template with Rabbitt AI branding.
 */
function buildEmailHtml(summary) {
  const summaryHtml = markdownToHtml(summary);

  return `
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body style="margin:0;padding:0;font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;background-color:#0f0f23;color:#ffffff;">
    <div style="max-width:680px;margin:0 auto;background-color:#1a1a2e;border-radius:12px;overflow:hidden;box-shadow:0 8px 32px rgba(0,0,0,0.4);">
      
      <!-- Header -->
      <div style="background:linear-gradient(135deg,#6C63FF 0%,#3B82F6 50%,#8B5CF6 100%);padding:32px 40px;text-align:center;">
        <h1 style="margin:0;font-size:28px;font-weight:700;color:#ffffff;letter-spacing:1px;">
          🐇 Rabbitt AI
        </h1>
        <p style="margin:8px 0 0;font-size:14px;color:rgba(255,255,255,0.85);font-weight:300;">
          Sales Insight Automator
        </p>
      </div>
      
      <!-- Title Bar -->
      <div style="background-color:#16213e;padding:20px 40px;border-bottom:1px solid rgba(108,99,255,0.2);">
        <h2 style="margin:0;font-size:20px;color:#6C63FF;font-weight:600;">
          📊 AI-Generated Sales Summary
        </h2>
        <p style="margin:6px 0 0;font-size:13px;color:#8892b0;">
          Auto-generated by Rabbitt AI's Sales Insight Engine
        </p>
      </div>
      
      <!-- Summary Content -->
      <div style="padding:30px 40px;font-size:15px;line-height:1.8;color:#ccd6f6;">
        <p>${summaryHtml}</p>
      </div>
      
      <!-- Footer -->
      <div style="background-color:#0d0d1a;padding:24px 40px;text-align:center;border-top:1px solid rgba(108,99,255,0.15);">
        <p style="margin:0;font-size:12px;color:#4a5568;">
          This report was auto-generated by <strong style="color:#6C63FF;">Rabbitt AI Sales Insight Automator</strong>.
        </p>
        <p style="margin:8px 0 0;font-size:11px;color:#3a4258;">
          Powered by Google Gemini AI &bull; &copy; 2026 Rabbitt AI
        </p>
      </div>
    </div>
  </body>
  </html>`;
}

/**
 * Send AI-generated sales summary to the recipient via Gmail SMTP using Nodemailer.
 */
async function sendEmail(recipient, summary) {
  if (!config.gmailUser || !config.gmailAppPassword) {
    throw new Error('Gmail credentials are not configured. Set GMAIL_USER and GMAIL_APP_PASSWORD.');
  }

  // Create Nodemailer transporter with Gmail
  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: config.gmailUser,
      pass: config.gmailAppPassword,
    },
  });

  const mailOptions = {
    from: `"Rabbitt AI" <${config.gmailUser}>`,
    to: recipient,
    subject: '📊 Your AI-Generated Sales Insight Report — Rabbitt AI',
    text: `Sales Insight Report\n\n${summary}\n\n---\nGenerated by Rabbitt AI Sales Insight Automator`,
    html: buildEmailHtml(summary),
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log(`✅ Email sent successfully to ${recipient}`);
    return true;
  } catch (error) {
    console.error(`❌ Failed to send email to ${recipient}:`, error.message);
    throw new Error(`Failed to send email: ${error.message}`);
  }
}

module.exports = { sendEmail };
